name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create-release.outputs.tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        name: create release
        id: create-release
        with:
          release-type: simple
          bump-minor-pre-major: true # remove this to enable breaking changes causing 1.0.0 tag
          changelog-types: |
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Patches", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false }
            ]
          extra-files: |
            SECURITY.md
            docs/guide/getting-started.md
            docs/pt-br/guide/getting-started.md
            docs/zh-hans/guide/getting-started.md
  build:
    name: Build release binaries
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # windows isn't working on windows right now, add it to this list once
        # I fix the code.
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          #- goarch: arm64
          #  goos: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute asdf version
        id: asdf-version
        shell: bash
        run: echo "version=$(./scripts/asdf-version)" >> "$GITHUB_OUTPUT"
      - name: Build Go binaries
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.23.4"
          binary_name: "asdf"
          project_path: ./cmd/asdf
          release_tag: ${{ needs.release.outputs.tag_name }}
          release_name: ${{ needs.release.outputs.tag_name }}
          ldflags: -s -X main.version=${{ steps.asdf-version.outputs.version }}
